#bin/bash

TOTAL_ANANAS=50

TOTAL_BANANA=4

TOTAL_WATERMELON=23

TOTAL_PANIER=1

TOTAL=$(($TOTAL_ANANAS + $((2 * $TOTAL_BANANA)) + $((3 * $TOTAL_WATERMELON)) + $TOTAL_PANIER))

echo "Le cout total est $TOTAL"